document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>头部</title>");
document.writeln("    <style type=\'text/css\'>");
document.writeln("        header {");
document.writeln("            height: 50px;");
document.writeln("            line-height: 50px;");
document.writeln("            background-color: #FF0B0C;");
document.writeln("            position: fixed;");
document.writeln("            top: 0;");
document.writeln("            left: 0;");
document.writeln("            width: 100%;");
document.writeln("            z-index: 99;");
document.writeln("        }");
document.writeln("        header .location {");
document.writeln("            display: block;");
document.writeln("            position: absolute;");
document.writeln("            left: 0;");
document.writeln("            top: 0;");
document.writeln("            color: white;");
document.writeln("            padding: 12.5px;");
document.writeln("            margin-left: 3%;");
document.writeln("        }");
document.writeln("        img {");
document.writeln("            width: 100%;");
document.writeln("            height: auto;");
document.writeln("            display: block;");
document.writeln("            border: 0;");
document.writeln("        }");
document.writeln("        header .location img {");
document.writeln("            width: 25px;");
document.writeln("        }");
document.writeln("        .flex-col {");
document.writeln("            display: block;");
document.writeln("            -webkit-box-flex: 1;");
document.writeln("            -webkit-flex: 1;");
document.writeln("            flex: 1;");
document.writeln("            width: 62%;");
document.writeln("            margin-left: 21%;");
document.writeln("            background-color: #fff;");
document.writeln("            margin: 10px auto 0 auto;");
document.writeln("            overflow: hidden;");
document.writeln("            position: relative;");
document.writeln("        }");
document.writeln("        .top-sch-box {");
document.writeln("            height: 0.6rem;");
document.writeln("            padding: 0 .8rem;");
document.writeln("            font-size: .36rem;");
document.writeln("            color: #999999;");
document.writeln("            -webkit-border-radius: 3px;");
document.writeln("            border-radius: 3px;");
document.writeln("        }");
document.writeln("        .index-searchArea .input-text-searchArea {");
document.writeln("            width: 90%;");
document.writeln("            height: 2rem;");
document.writeln("            outline: none;");
document.writeln("            border: none;");
document.writeln("            float: left;");
document.writeln("            font-size: 0.4rem;");
document.writeln("            line-height: 0.5rem;");
document.writeln("            padding-left: .3rem;");
document.writeln("        }");
document.writeln("        input {");
document.writeln("            color: inherit;");
document.writeln("            font: inherit;");
document.writeln("            font-size: inherit;");
document.writeln("            line-height: inherit;");
document.writeln("            margin: 0;");
document.writeln("        }");
document.writeln("        .input-searchBtn[type=\'button\'] {");
document.writeln("            font-family: \'freshregular\';");
document.writeln("            background: none;");
document.writeln("            border: none;");
document.writeln("            color: grey;");
document.writeln("            position: absolute;");
document.writeln("            left: -30px;");
document.writeln("            top: -9px;");
document.writeln("            outline: none;");
document.writeln("            font-size: .45rem;");
document.writeln("        }");
document.writeln("        .index-searchArea .input-searchBtn {");
document.writeln("            width: 9%;");
document.writeln("            color: #000;");
document.writeln("            float: right;");
document.writeln("            position: absolute;");
document.writeln("            right: 3%;");
document.writeln("        }");
document.writeln("        body{");
document.writeln("            margin: 0;");
document.writeln("            padding: 0;");
document.writeln("        }");
document.writeln("        * {");
document.writeln("            font-family: \'微软雅黑\';");
document.writeln("            -webkit-box-sizing: border-box;");
document.writeln("            -moz-box-sizing: border-box;");
document.writeln("            box-sizing: border-box;");
document.writeln("        }");
document.writeln("        @font-face {");
document.writeln("            font-family:\'freshregular\';");
document.writeln("            src:url(\'../css/fonts/fresh-webfont.woff\') format(\'woff\'),");
document.writeln("            url(\'../css/fonts/fresh-webfont.ttf\') format(\'truetype\'),");
document.writeln("            url(\'../css/fonts/fresh-webfont.svg#freshregular\') format(\'svg\');");
document.writeln("            font-weight: normal;");
document.writeln("            font-style: normal;");
document.writeln("        }");
document.writeln(".black_overlay{");
document.writeln("			display: none;");
document.writeln("			position: absolute;");
document.writeln("			top: 0%;");
document.writeln("			left: 0%;");
document.writeln("			width: 100%;");
document.writeln("			height: 100%;");
document.writeln("			background-color: black;");
document.writeln("			z-index:1001;");
document.writeln("			-moz-opacity: 0.8;");
document.writeln("			opacity:.80;");
document.writeln("			filter: alpha(opacity=88);");
document.writeln("		}");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<!--header-->");
document.writeln("<header >");
document.writeln("    <a href=\'../Main/scan.jsp\'  class=\'location\' id=\'location\' data-title-type=\'native\' style=\'display: flex;align-items: center\'>");
document.writeln("        <img src=\'../images/scan.png\' style=\'align-items: center;\' />");
document.writeln("    </a>");
document.writeln("");
document.writeln("    <div class=\'top-sch-box flex-col logoIcon\'>");
document.writeln("        <a>");
document.writeln("            <!--<ul>-->");
document.writeln("                <!--<li>扫码点菜</li>-->");
document.writeln("            <!--</ul>-->");
document.writeln("            <aside class=\'index-searchArea\'>");
document.writeln("                <input class=\'input-text-searchArea\' type=\'text\' placeholder=\'请输入餐品\' />");
document.writeln("                <input type=\'button\' value=\'&#63;\' class=\'input-searchBtn\' />");
document.writeln("            </aside>");
document.writeln("        </a>");
document.writeln("    </div>");
document.writeln("</header>");
document.writeln("</body>");
document.writeln("</html>");